### ISSUE TITLE
language - name collision

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-engine#493]
When partial expected `language` property it comes to the collision with  `translate` tag 

```html
<script i18n yaml>
foo:
-'bar'
-'bar'
</script>
<layout language="{language}">
  <translate foo>
</layout>
```

```
TypeError: Cannot read property 'language' of undefined
    at render (eval at generate (node_modules/pure-engine/src/Compiler.js:148:22), <anonymous>:63:56)
    at View.render [as engine] (/node_modules/express-pure-engine/index.js:33:20)
```

**Comment by pkonieczniak** [comment]
```js
function render(__o, __e) {
 function translate(key, language) {
  const translations = {};
  const languages = ["pl", "en"];
  const index = languages.indexOf(language);
  return translations[key][index];
 }
var __t = "<!doctype html><html lang=\"";
__t += __e(__o.language);
__t += "\"><body>";
__t += translate("foo", __o.__o.language);
__t += "</body></html>";
return __t;
}
```
